### ISSUE TITLE
dataset replication

### ISSUE THREAD

**Issue by hhzhao0525** [Vanint/DatasetExpansion#5]
Is it possible to perform data augmentation with a homemade railroad scene dataset, and if so, how should it be done? Thanks.

**Comment by YifanZhang07** [comment]
Performing dataset expansion on a homemade railroad scene dataset is indeed more complex than typical natural image classification datasets due to the need to adhere to specific railroad rules. A potential approach is to first attempt a quick fine-tuning of the Stable Diffusion on your target small-scale homemade railroad scene dataset. Based on the fine-tuned stable diffusion, you can then proceed with dataset expansion following our proposed method. This is an initial strategy to test its feasibility. If it proves ineffective, you might need to design further expansion guidance based on railroad rules for more customized augmentation.
